name: 'Compile libfibre'
description: 'Compiles libfibre for the specified target'

inputs:
  target:
    description: |
      The build target on which the compiled libfibre is supposed to run.
      The supported targets are all strings "target" for which a file
      cpp/[target].config exists.
    required: true

runs:
  using: 'docker'
  image: fibreframework/compiler:latest
  args: ['cpp/configs/${{ inputs.target }}.config']

branding:
  icon: terminal
  color: green
