
name: Tests

# new draft: https://godbolt.org/z/qMa4YG

on:
  pull_request:
    branches: [master, devel]
  push:
    branches: [master, devel]

jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        target: [linux-amd64, linux-armhf, macos-x86, wasm, windows-amd64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - uses: ./.github/actions/compile
        with:
          target: ${{ matrix.target }}
      - name: List outputs
        run: ls -la cpp/build/
      - uses: actions/upload-artifact@v2
        with:
          name: libfibre-${{ matrix.target }}
          path: cpp/build/libfibre-*

  test-pyfibre:
    needs: [compile]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Display structure of downloaded files
        run: ls -R artifacts
      - run: |
          echo "not implemented yet"
          false

  formatting:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04 # need a recent clang-format
    steps:
      - uses: actions/checkout@v2

      - name: Check C++ Formatting
        run: |
          clang-format --version
          # TODO: we run this only on one file for now until we have it properly configured
          clang-format -style=file --Werror --dry-run test/test_server.cpp

  #    TODO: check if interface_generator outputs the same thing with Python 3.5 and Python 3.8
