name: Tests

on:
  pull_request:
    branches: [master, devel]
  push:
    branches: [master, devel]

jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, target: local}

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/compile
        with:
          target: ${{ matrix.local }}

  formatting:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04 # need a recent clang-format
    steps:
      - uses: actions/checkout@v2

      - name: Check C++ Formatting
        run: |
          clang-format --version
          # TODO: we run this only on one file for now until we have it properly configured
          clang-format -style=file --Werror --dry-run test/test_server.cpp

  #    TODO: check if interface_generator outputs the same thing with Python 3.5 and Python 3.8
